/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportNewRouteImport } from './routes/report.new'
import { Route as ReportIdRouteImport } from './routes/report.$id'
import { Route as ProposalNewRouteImport } from './routes/proposal.new'
import { Route as ProposalIdRouteImport } from './routes/proposal.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportNewRoute = ReportNewRouteImport.update({
  id: '/report/new',
  path: '/report/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalNewRoute = ProposalNewRouteImport.update({
  id: '/proposal/new',
  path: '/proposal/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalIdRoute = ProposalIdRouteImport.update({
  id: '/proposal/$id',
  path: '/proposal/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/proposal/$id': typeof ProposalIdRoute
  '/proposal/new': typeof ProposalNewRoute
  '/report/$id': typeof ReportIdRoute
  '/report/new': typeof ReportNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/proposal/$id': typeof ProposalIdRoute
  '/proposal/new': typeof ProposalNewRoute
  '/report/$id': typeof ReportIdRoute
  '/report/new': typeof ReportNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/proposal/$id': typeof ProposalIdRoute
  '/proposal/new': typeof ProposalNewRoute
  '/report/$id': typeof ReportIdRoute
  '/report/new': typeof ReportNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/proposal/$id'
    | '/proposal/new'
    | '/report/$id'
    | '/report/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/proposal/$id' | '/proposal/new' | '/report/$id' | '/report/new'
  id:
    | '__root__'
    | '/'
    | '/proposal/$id'
    | '/proposal/new'
    | '/report/$id'
    | '/report/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProposalIdRoute: typeof ProposalIdRoute
  ProposalNewRoute: typeof ProposalNewRoute
  ReportIdRoute: typeof ReportIdRoute
  ReportNewRoute: typeof ReportNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/new': {
      id: '/report/new'
      path: '/report/new'
      fullPath: '/report/new'
      preLoaderRoute: typeof ReportNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/new': {
      id: '/proposal/new'
      path: '/proposal/new'
      fullPath: '/proposal/new'
      preLoaderRoute: typeof ProposalNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/$id': {
      id: '/proposal/$id'
      path: '/proposal/$id'
      fullPath: '/proposal/$id'
      preLoaderRoute: typeof ProposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProposalIdRoute: ProposalIdRoute,
  ProposalNewRoute: ProposalNewRoute,
  ReportIdRoute: ReportIdRoute,
  ReportNewRoute: ReportNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
